(function(CbnForm) {
	
	/**
	 * Defines a form input element for use with `cbn-form` components suite.
	 * 
	 * This behavior provides normalized form input semantics:
	 * 
	 * - the {@link #value} property provides access to the input's value;
	 * - when the value is changed, the element fires a `value-changed` event;
	 * - you can see whether the value was directly changed by the user or was indirectly changed by checking the event's 
	 *   `event.detail.indirect` boolean value;
	 * - if you want to set the value and avoid firing this event, see {@link #_setIndirectValue}.
	 * 
	 * You should include this behavior after `CbnForm.FormElement`.
	 * 
	 * @polymerBehavior
	 */
	CbnForm.InputElementImpl = {
		
		properties: {
			
			/**
			 * Input's name. 
			 * 
			 * It is used as form model binding path.
			 * For example, if the name is 'name.first_name' will bind to `model['name']['first_name']`.
			 */
			name: {
				type: String,
				value: ''
			},
			
			/**
			 * Input's value attribute.
			 * 
			 * Should be String for most of the cases, Array for inputs with multiple values and Object for
			 * special input types (e.g. file).
			 * 
			 * @type {String|Number|Array|Object}
			 */
			value: {
				type: String,
				value: '',
				notify: false, /** event is manually fired, see {@link #_fe_valueChanged} */
				observer: '_fe_valueChanged'
			},
			
			/**
			 * Input's default value.
			 * Will be automatically set if the model value is empty.
			 * 
			 * @type {String|Number|Array|Object}
			 */
			defaultValue: {
				type: String,
				value: ''
			},
			
			/**
			 * This input provides a model value.
			 */
			_hasModelValue: {
				type: Boolean,
				value: true
			}
			
		},
		
		/**
		 * Defines the common dynamic attributes for all form elements.
		 */
		dynamicAttributes: {
			"type" 		: { type: 'attribute' },
			"name" 		: { type: 'attribute' },
			"defaultValue" : { type: 'attribute' },
			"preview"	: { type: 'attribute' }
		},
		
		/**
		 * Will automatically be set to true if the {@link #value} property is indirectly changed (i.e. from the form's 
		 * model).
		 * 
		 * If used, the `value-changed` event generated by the source component (which made the changes).
		 * 
		 * @type {Boolean}
		 */
		_inputValueIndirectlyChanged: false,
		
		
		// Events
		
		/**
		 * Notifies the other components that the input's value is changed.
		 * 
		 * If you want to customize / avoid firing this event while changing the input's value, see {@link #_setIndirectValue}.
		 * 
		 * @event value-changed
		 * @detail {mixed}   value The new value of the input.
		 * @detail {Boolean} indirect If the value was indirectly changed (e.g. by modifying the form model)
		 */
		
		
		// Observers / Event handlers
		
		/**
		 * Observer for the form element's {@link #value} property.
		 * 
		 * It manually fires the 'value-changed' event conditionally if {@link #_inputValueIndirectlyChanged} is false.
		 * 
		 * @param {mixed} newValue The new value that was set.
		 */
		_fe_valueChanged: function(newValue) {
			if (this._inputValueIndirectlyChanged) return;
			
			this.fire('value-changed', {
				value: newValue
			});
		},
		
		
		// Protected Methods: (to be used by `cbn-form` components / behavior users)
		
		/**
		 * Changes the input's value programmatically.
		 * 
		 * Should fire notification events (if {@link #_inputValueIndirectlyChanged} is not true).
		 * 
		 * @param value The value to set.
		 * @protected
		 */
		_setValue: function (value) {
			// let the _fe_valueChanged observer handle notifications
			this.value = value;
		},
		
		/**
		 * Changes the input's value indirectly (fires a custom marked `value-changed` event).
		 * 
		 * This is used when the value is changed as a result of a form model change.
		 * 
		 * @param {*}              value The value to set.
		 * @param {object|Boolean} [notification] Notification details to emit. Defaults to `{indirect: true}`. 
		 *                         Set to false to avoid firing the `value-changed` event.
		 * @protected
		 */
		_setIndirectValue: function(value, notification) {
			this._inputValueIndirectlyChanged = true;
			// the _fe_valueChanged observer will synchronously fire and skip the `value-changed` event
			this._setValue(value);
			this._inputValueIndirectlyChanged = false;
			
			if (notification !== false) {
				if (!notification) notification = { indirect: true };
				this.fire('value-changed', this.extend({
					value: value
				}, notification));
			}
		}
		
	};
	
	CbnForm.InputElement = [ CbnForm.FormElement, CbnForm.InputElementImpl ];
	
	/**
	 * The InputElement interface declaration (for JSDoc purposes).
	 * 
	 * @typedef {Object} CbnForm.InputElement
	 * 
	 * @property {String} name Form element's name.
	 * @property {*} value Input value.
	 * @property {*} defaultValue Input's default value.
	 * @property {Boolean} _hasModelValue Whether the input has a value.
	 * @property {HTMLElement} parentForm The element's parent form container.
	 * 
	 * Methods:
	 * @property {Function} _setValue Programmatically set the input's value.
	 * @property {Function} _setIndirectValue Set the input's value indirectly.
	 */
	
})(CbnForm);
